"""Validate the reviewed link registry and generate the offline runtime file.

Research candidates and proposed new adventures are deliberately not inputs.
Default/--check detects stale output; --write explicitly regenerates it.
"""
import datetime
import argparse
import json
import pathlib
import re
from urllib.parse import urlsplit

ROOT = pathlib.Path(__file__).resolve().parents[1]


def build():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = json.loads((ROOT / 'data/viator-links.json').read_text(encoding='utf-8'))
    assert source['schema_version'] == 1
    adventures = {a['id']: a for a in json.loads((ROOT / 'data/adventures.json').read_text(encoding='utf-8'))}
    links = {}
    for r in source['links']:
        a = adventures[r['adventure_id']]
        assert str(a['id']) not in links, f"Duplicate adventure {a['id']}"
        assert r['status'] == 'verified'
        assert r['country'] == a['country'] and r['place'] == a['place']
        assert r['adventure_title'] == a['title']
        assert a.get('availability', {}).get('status') != 'unavailable'
        assert r['match_type'] in ('exact', 'guided_option')
        assert r['match_note'].strip()
        assert r['verification'] in ('product_page', 'product_api')
        if r['verification'] == 'product_page':
            assert r['evidence_url'].startswith('https://www.viator.com/tours/')
        else:
            assert r['evidence_url'] == 'https://api.viator.com/partner/products/' + r['product_code']
        assert r['product_status'] == 'ACTIVE', 'Inactive products must never receive a booking link'
        assert r['product_status_evidence'] == 'https://api.viator.com/partner/products/' + r['product_code']
        assert datetime.datetime.fromisoformat(r['product_status_checked_at']).date() <= datetime.date.today()
        assert r['schedule_status'] == 'current_or_future_schedule'
        assert r['schedule_evidence'] == 'https://api.viator.com/partner/availability/schedules/' + r['product_code']
        assert datetime.datetime.fromisoformat(r['schedule_checked_at']).date() <= datetime.date.today()
        assert datetime.date.fromisoformat(r['checked_at']) <= datetime.date.today()
        u = urlsplit(r['viator_url'])
        assert u.scheme == 'https' and u.netloc == 'www.viator.com'
        assert not u.query and not u.fragment
        assert re.fullmatch(r'/tours/[^/]+/[^/]+/d\d+-[A-Za-z0-9_]+', u.path)
        assert u.path.endswith('-' + r['product_code'])
        links[str(a['id'])] = {k: r[k] for k in (
            'country', 'place', 'adventure_title', 'viator_url', 'product_code', 'product_title', 'match_type', 'match_note', 'checked_at', 'status')}
    body = json.dumps(dict(sorted(links.items(), key=lambda x: int(x[0]))), ensure_ascii=True, indent=2)
    rendered = '// Generated by tools/build_booking_links.py from reviewed per-adventure links.\nconst VIATOR_BOOKING_LINKS = Object.freeze(' + body + ');\n'
    out = ROOT / 'booking-links.js'
    if not args.write:
        assert out.read_text(encoding='utf-8') == rendered, 'Run tools/build_booking_links.py --write'
    else:
        out.write_text(rendered, encoding='utf-8')
    print(f'{len(links)} reviewed per-adventure Viator links validated')


if __name__ == '__main__':
    build()
