"""Write countries.js from the registry in tools/countries.py.

One list, one place. world.js used to carry its own hand-kept table of names
and flags, which drifted from the geography checker's table every time a
country was added. Both now come from here.

    python tools/build_countries.py

Writes countries.js.
"""
import io
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from countries import ADVISORIES, COUNTRIES          # noqa: E402

OUT = 'countries.js'


def flag(code):
    """A flag emoji is the ISO code written in regional indicator symbols."""
    return ''.join(chr(0x1F1E6 + ord(c) - ord('A')) for c in code)


def main():
    names = {c: v[0] for c, v in COUNTRIES.items()}
    cont = {c: v[1] for c, v in COUNTRIES.items()}
    flags = {c: flag(c) for c in COUNTRIES}
    adv = {c: {'level': lvl, 'note': note} for c, (lvl, note) in ADVISORIES.items()}

    for code in adv:
        if code not in COUNTRIES:
            raise SystemExit('advisory for unknown country %r' % code)

    body = '''// Generated by tools/build_countries.py - do not edit by hand.
// Edit tools/countries.py and re-run it.
//
// Every country the app knows, whether or not it holds any adventures yet.
// The continent lists are built from this rather than from the adventure data,
// so a country with nothing in it still appears, honestly marked as empty,
// instead of quietly not existing.

const COUNTRY_NAME = @NAMES@;
const COUNTRY_FLAG = @FLAGS@;
const COUNTRY_CONT = @CONT@;

/* Places where the honest advice is not when to go but whether to.
 *
 * 'avoid' is do-not-travel. 'care' means part of the country, or a situation
 * that moves. Either way the app says to check current government advice
 * rather than trusting a line of text baked into an app months ago.
 */
const ADVISORY = @ADV@;

function advisoryFor(code) {
  return ADVISORY[code] || null;
}

// Countries in one continent, most content first, then the empty ones by name.
function countriesIn(continent, countFn) {
  const codes = Object.keys(COUNTRY_CONT).filter(c => COUNTRY_CONT[c] === continent);
  return codes.sort((a, b) => {
    const d = (countFn(b) || 0) - (countFn(a) || 0);
    return d || COUNTRY_NAME[a].localeCompare(COUNTRY_NAME[b]);
  });
}
'''
    for token, value in [
        ('@NAMES@', json.dumps(names, ensure_ascii=False, sort_keys=True, indent=0)
                        .replace('\n', ' ').replace('{ ', '{').replace(' }', '}')),
        ('@FLAGS@', json.dumps(flags, ensure_ascii=False, sort_keys=True,
                               separators=(',', ':'))),
        ('@CONT@', json.dumps(cont, ensure_ascii=False, sort_keys=True,
                              separators=(',', ':'))),
        ('@ADV@', json.dumps(adv, ensure_ascii=False, sort_keys=True, indent=2)),
    ]:
        body = body.replace(token, value)

    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(body)
    by_cont = {}
    for c, name in cont.items():
        by_cont[name] = by_cont.get(name, 0) + 1
    print('%d countries written to %s' % (len(COUNTRIES), OUT))
    for name in sorted(by_cont, key=lambda k: -by_cont[k]):
        print('  %-15s %d' % (name, by_cont[name]))
    print('%d advisories (%d do-not-travel)'
          % (len(adv), sum(1 for a in adv.values() if a['level'] == 'avoid')))


if __name__ == '__main__':
    main()
