"""Bake a real coastline into a dot-grid mask.

The map used to draw its dots straight from CONTINENT_BOXES, which is a handful
of rectangles. That is fine for deciding which continent a tap landed in, but as
a picture it gave every landmass square corners. This takes Natural Earth's
110m land polygons, rasterises them onto the same grid the canvas draws, and
writes the result out as a packed bitmask.

The mask says only "is there land here". Colour still comes from continentAt(),
so the boxes remain the single source of truth for which continent is which.

    python tools/build_map.py

Writes land.js. Re-run only if STEP/LAT_TOP/LAT_BOTTOM below change.
"""
import base64
import io
import json
import urllib.request

SRC = 'https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json'
OUT = 'land.js'

# Must match drawWorldMap() in world.js.
STEP = 1.6
LAT_TOP, LAT_BOTTOM = 78.0, -58.0
COLS = int(round(360 / STEP))              # 225
ROWS = int(round((LAT_TOP - LAT_BOTTOM) / STEP))   # 85


def load_rings():
    """Decode the TopoJSON into flat lon/lat rings."""
    topo = json.loads(urllib.request.urlopen(SRC, timeout=60).read())
    sx, sy = topo['transform']['scale']
    tx, ty = topo['transform']['translate']

    arcs = []
    for arc in topo['arcs']:
        x = y = 0
        pts = []
        for dx, dy in arc:
            x += dx
            y += dy
            pts.append((x * sx + tx, y * sy + ty))
        arcs.append(pts)

    def stitch(idxs):
        ring = []
        for i in idxs:
            pts = arcs[~i][::-1] if i < 0 else arcs[i]
            ring.extend(pts[1:] if ring else pts)
        return ring

    rings = []
    for geom in topo['objects']['land']['geometries']:
        polys = geom['arcs'] if geom['type'] == 'MultiPolygon' else [geom['arcs']]
        for poly in polys:
            for ring in poly:
                r = stitch(ring)
                if len(r) > 2:
                    rings.append(r)
    return rings


def rasterise(rings):
    """Scanline fill: for each dot row, find where the coastline crosses it."""
    edges = []
    for ring in rings:
        for i in range(len(ring)):
            x0, y0 = ring[i]
            x1, y1 = ring[(i + 1) % len(ring)]
            if y0 != y1:
                edges.append((x0, y0, x1, y1))

    grid = bytearray(COLS * ROWS)
    for row in range(ROWS):
        lat = LAT_TOP - row * STEP - STEP / 2
        xs = []
        for x0, y0, x1, y1 in edges:
            if (y0 <= lat < y1) or (y1 <= lat < y0):
                xs.append(x0 + (lat - y0) * (x1 - x0) / (y1 - y0))
        xs.sort()
        # Even-odd: inside between each pair of crossings.
        for i in range(0, len(xs) - 1, 2):
            a, b = xs[i], xs[i + 1]
            c0 = int((a + 180) / STEP)
            c1 = int((b + 180) / STEP)
            for col in range(max(c0, 0), min(c1 + 1, COLS)):
                lon = -180 + col * STEP + STEP / 2
                if a <= lon <= b:
                    grid[row * COLS + col] = 1
    return grid


def pack(grid):
    """One bit per dot, row-major, MSB first."""
    out = bytearray((len(grid) + 7) // 8)
    for i, v in enumerate(grid):
        if v:
            out[i >> 3] |= 0x80 >> (i & 7)
    return base64.b64encode(bytes(out)).decode('ascii')


def main():
    rings = load_rings()
    grid = rasterise(rings)
    land = sum(grid)
    blob = pack(grid)

    body = f'''// Generated by tools/build_map.py - do not edit by hand.
// Natural Earth 110m land, rasterised to the dot grid the world map draws.
// {COLS} x {ROWS} dots at {STEP} degrees, latitudes {LAT_TOP} down to {LAT_BOTTOM}.
const LAND = {{
  cols: {COLS}, rows: {ROWS}, step: {STEP},
  top: {LAT_TOP}, bottom: {LAT_BOTTOM},
  bits: '{blob}',
}};

// Unpacked once on first use; the canvas redraws often enough to care.
LAND.mask = null;
function landAt(row, col) {{
  if (!LAND.mask) {{
    const raw = atob(LAND.bits);
    const m = new Uint8Array(LAND.cols * LAND.rows);
    for (let i = 0; i < m.length; i++) {{
      m[i] = (raw.charCodeAt(i >> 3) >> (7 - (i & 7))) & 1;
    }}
    LAND.mask = m;
  }}
  if (row < 0 || row >= LAND.rows || col < 0 || col >= LAND.cols) return 0;
  return LAND.mask[row * LAND.cols + col];
}}
'''
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(body)
    pct = 100 * land / len(grid)
    print(f'{COLS} x {ROWS} = {len(grid)} dots, {land} land ({pct:.1f}%)')
    print(f'{OUT} written, {len(blob)} chars of base64')


if __name__ == '__main__':
    main()
