"""The single list of countries the app knows about.

Every sovereign state, plus the territories that are worth listing separately
because they sit on a different continent to the country that governs them -
French Guiana is in South America, Greenland in North America, Reunion in
Africa. Listing them under France, Denmark and France again would put them in
the wrong place on the map and in the wrong part of the app.

Continents follow the app's scheme: the Middle East is split out of Asia, and
Central America and the Caribbean belong to North America.

Flags are not stored. A flag emoji is just the two letters of the ISO code as
regional indicator symbols, so it is derived wherever it is needed.

    code: (name, continent, latitude, longitude)

The coordinates are a rough point on land, used to test that a country lands
inside its own continent box on the map. They are not adventure coordinates.
"""

COUNTRIES = {
    # ── Oceania ───────────────────────────────────────────────────────
    'AU': ('Australia', 'Oceania', -25.0, 134.0),
    'NZ': ('New Zealand', 'Oceania', -41.0, 174.0),
    'PG': ('Papua New Guinea', 'Oceania', -6.3, 144.0),
    'FJ': ('Fiji', 'Oceania', -17.8, 178.0),
    'SB': ('Solomon Islands', 'Oceania', -9.6, 160.2),
    'VU': ('Vanuatu', 'Oceania', -15.4, 167.0),
    'NC': ('New Caledonia', 'Oceania', -21.3, 165.6),
    'PF': ('French Polynesia', 'Oceania', -17.6, -149.4),
    'WS': ('Samoa', 'Oceania', -13.6, -172.4),
    'TO': ('Tonga', 'Oceania', -21.2, -175.2),
    'CK': ('Cook Islands', 'Oceania', -21.2, -159.8),
    'NU': ('Niue', 'Oceania', -19.1, -169.9),
    'NF': ('Norfolk Island', 'Oceania', -29.0, 167.9),
    'FM': ('Micronesia', 'Oceania', 7.4, 150.6),
    'MH': ('Marshall Islands', 'Oceania', 7.1, 171.2),
    'KI': ('Kiribati', 'Oceania', 1.9, -157.4),
    'TV': ('Tuvalu', 'Oceania', -8.5, 179.2),
    'NR': ('Nauru', 'Oceania', -0.5, 166.9),
    'PW': ('Palau', 'Oceania', 7.5, 134.6),
    'GU': ('Guam', 'Oceania', 13.4, 144.8),
    'AS': ('American Samoa', 'Oceania', -14.3, -170.7),
    'WF': ('Wallis & Futuna', 'Oceania', -13.3, -176.2),
    'TK': ('Tokelau', 'Oceania', -9.2, -171.8),
    'MP': ('Northern Mariana Islands', 'Oceania', 15.2, 145.8),

    # ── Asia ──────────────────────────────────────────────────────────
    'JP': ('Japan', 'Asia', 36.2, 138.3),
    'CN': ('China', 'Asia', 35.9, 104.2),
    'KR': ('South Korea', 'Asia', 36.5, 127.8),
    'KP': ('North Korea', 'Asia', 40.3, 127.5),
    'TW': ('Taiwan', 'Asia', 23.7, 121.0),
    'HK': ('Hong Kong', 'Asia', 22.3, 114.2),
    'MO': ('Macau', 'Asia', 22.2, 113.55),
    'MN': ('Mongolia', 'Asia', 46.9, 103.8),
    'TH': ('Thailand', 'Asia', 15.0, 101.0),
    'VN': ('Vietnam', 'Asia', 16.0, 106.5),
    'KH': ('Cambodia', 'Asia', 12.6, 104.9),
    'LA': ('Laos', 'Asia', 18.2, 103.9),
    'MM': ('Myanmar', 'Asia', 21.9, 96.0),
    'MY': ('Malaysia', 'Asia', 4.2, 102.0),
    'SG': ('Singapore', 'Asia', 1.35, 103.8),
    'BN': ('Brunei', 'Asia', 4.5, 114.7),
    'ID': ('Indonesia', 'Asia', -2.5, 118.0),
    'TL': ('Timor-Leste', 'Asia', -8.8, 125.7),
    'PH': ('Philippines', 'Asia', 12.9, 122.0),
    'IN': ('India', 'Asia', 22.0, 79.0),
    'NP': ('Nepal', 'Asia', 28.3, 84.1),
    'BT': ('Bhutan', 'Asia', 27.4, 90.4),
    'BD': ('Bangladesh', 'Asia', 23.7, 90.3),
    'LK': ('Sri Lanka', 'Asia', 7.6, 80.7),
    'MV': ('Maldives', 'Asia', 3.2, 73.2),
    'PK': ('Pakistan', 'Asia', 30.4, 69.3),
    'AF': ('Afghanistan', 'Asia', 33.9, 66.0),
    'KZ': ('Kazakhstan', 'Asia', 48.0, 67.0),
    'UZ': ('Uzbekistan', 'Asia', 41.4, 64.6),
    'TM': ('Turkmenistan', 'Asia', 39.0, 59.6),
    'KG': ('Kyrgyzstan', 'Asia', 41.2, 74.8),
    'TJ': ('Tajikistan', 'Asia', 38.9, 71.3),

    # ── Middle East ───────────────────────────────────────────────────
    'AE': ('United Arab Emirates', 'Middle East', 24.0, 54.0),
    'OM': ('Oman', 'Middle East', 21.0, 57.0),
    'QA': ('Qatar', 'Middle East', 25.3, 51.2),
    'BH': ('Bahrain', 'Middle East', 26.0, 50.55),
    'KW': ('Kuwait', 'Middle East', 29.3, 47.5),
    'SA': ('Saudi Arabia', 'Middle East', 24.0, 45.0),
    'YE': ('Yemen', 'Middle East', 15.5, 47.5),
    'JO': ('Jordan', 'Middle East', 31.2, 36.5),
    'LB': ('Lebanon', 'Middle East', 33.9, 35.9),
    'IL': ('Israel', 'Middle East', 31.4, 34.9),
    'PS': ('Palestine', 'Middle East', 31.9, 35.3),
    'SY': ('Syria', 'Middle East', 35.0, 38.0),
    'IQ': ('Iraq', 'Middle East', 33.0, 43.7),
    'IR': ('Iran', 'Middle East', 32.5, 54.0),
    'TR': ('Turkiye', 'Middle East', 39.0, 35.0),
    'GE': ('Georgia', 'Middle East', 42.2, 43.4),
    'AM': ('Armenia', 'Middle East', 40.3, 45.0),
    'AZ': ('Azerbaijan', 'Middle East', 40.3, 47.8),
    'CY': ('Cyprus', 'Middle East', 35.0, 33.2),

    # ── Europe ────────────────────────────────────────────────────────
    'GB': ('United Kingdom', 'Europe', 54.0, -2.0),
    'IE': ('Ireland', 'Europe', 53.2, -8.0),
    'FR': ('France', 'Europe', 46.6, 2.5),
    'ES': ('Spain', 'Europe', 40.2, -3.6),
    'PT': ('Portugal', 'Europe', 39.6, -8.0),
    'IT': ('Italy', 'Europe', 42.8, 12.6),
    'DE': ('Germany', 'Europe', 51.2, 10.4),
    'AT': ('Austria', 'Europe', 47.6, 14.1),
    'CH': ('Switzerland', 'Europe', 46.8, 8.2),
    'NL': ('Netherlands', 'Europe', 52.2, 5.6),
    'BE': ('Belgium', 'Europe', 50.6, 4.6),
    'LU': ('Luxembourg', 'Europe', 49.8, 6.1),
    'DK': ('Denmark', 'Europe', 56.0, 9.5),
    'NO': ('Norway', 'Europe', 61.5, 9.0),
    'SE': ('Sweden', 'Europe', 62.0, 15.5),
    'FI': ('Finland', 'Europe', 64.0, 26.0),
    'IS': ('Iceland', 'Europe', 64.9, -18.6),
    'EE': ('Estonia', 'Europe', 58.7, 25.5),
    'LV': ('Latvia', 'Europe', 56.9, 24.9),
    'LT': ('Lithuania', 'Europe', 55.3, 23.9),
    'PL': ('Poland', 'Europe', 52.1, 19.4),
    'CZ': ('Czechia', 'Europe', 49.8, 15.5),
    'SK': ('Slovakia', 'Europe', 48.7, 19.7),
    'HU': ('Hungary', 'Europe', 47.2, 19.4),
    'SI': ('Slovenia', 'Europe', 46.1, 14.8),
    'HR': ('Croatia', 'Europe', 45.2, 16.4),
    'BA': ('Bosnia & Herzegovina', 'Europe', 44.0, 17.8),
    'RS': ('Serbia', 'Europe', 44.2, 20.8),
    'ME': ('Montenegro', 'Europe', 42.8, 19.2),
    'XK': ('Kosovo', 'Europe', 42.6, 20.9),
    'MK': ('North Macedonia', 'Europe', 41.6, 21.7),
    'AL': ('Albania', 'Europe', 41.1, 20.1),
    'GR': ('Greece', 'Europe', 39.5, 22.0),
    'BG': ('Bulgaria', 'Europe', 42.7, 25.2),
    'RO': ('Romania', 'Europe', 45.9, 25.0),
    'MD': ('Moldova', 'Europe', 47.2, 28.6),
    'UA': ('Ukraine', 'Europe', 49.0, 31.2),
    'BY': ('Belarus', 'Europe', 53.7, 27.9),
    'RU': ('Russia', 'Europe', 56.0, 38.0),
    'MT': ('Malta', 'Europe', 35.9, 14.4),
    'AD': ('Andorra', 'Europe', 42.5, 1.6),
    'MC': ('Monaco', 'Europe', 43.74, 7.42),
    'SM': ('San Marino', 'Europe', 43.94, 12.46),
    'LI': ('Liechtenstein', 'Europe', 47.15, 9.55),
    'FO': ('Faroe Islands', 'Europe', 62.0, -6.8),
    'GI': ('Gibraltar', 'Europe', 36.14, -5.35),
    'JE': ('Jersey', 'Europe', 49.2, -2.1),
    'IM': ('Isle of Man', 'Europe', 54.2, -4.5),

    # ── North America ─────────────────────────────────────────────────
    'US': ('United States', 'North America', 39.5, -98.5),
    'CA': ('Canada', 'North America', 56.0, -106.0),
    'MX': ('Mexico', 'North America', 23.6, -102.5),
    'GL': ('Greenland', 'North America', 72.0, -42.0),
    'GT': ('Guatemala', 'North America', 15.5, -90.3),
    'BZ': ('Belize', 'North America', 17.2, -88.7),
    'SV': ('El Salvador', 'North America', 13.8, -88.9),
    'HN': ('Honduras', 'North America', 14.8, -86.6),
    'NI': ('Nicaragua', 'North America', 12.9, -85.2),
    'CR': ('Costa Rica', 'North America', 9.8, -84.0),
    'PA': ('Panama', 'North America', 8.5, -80.1),
    'CU': ('Cuba', 'North America', 21.7, -78.9),
    'JM': ('Jamaica', 'North America', 18.1, -77.3),
    'HT': ('Haiti', 'North America', 19.0, -72.4),
    'DO': ('Dominican Republic', 'North America', 18.8, -70.4),
    'BS': ('Bahamas', 'North America', 24.7, -77.9),
    'PR': ('Puerto Rico', 'North America', 18.2, -66.5),
    'TT': ('Trinidad & Tobago', 'North America', 10.5, -61.3),
    'BB': ('Barbados', 'North America', 13.2, -59.5),
    'LC': ('Saint Lucia', 'North America', 13.9, -61.0),
    'GD': ('Grenada', 'North America', 12.1, -61.7),
    'VC': ('St Vincent & Grenadines', 'North America', 13.2, -61.2),
    'AG': ('Antigua & Barbuda', 'North America', 17.1, -61.8),
    'DM': ('Dominica', 'North America', 15.4, -61.4),
    'KN': ('St Kitts & Nevis', 'North America', 17.3, -62.7),
    'AW': ('Aruba', 'North America', 12.5, -70.0),
    'CW': ('Curacao', 'North America', 12.2, -69.0),
    'KY': ('Cayman Islands', 'North America', 19.3, -81.2),
    'TC': ('Turks & Caicos', 'North America', 21.7, -71.7),
    'VG': ('British Virgin Islands', 'North America', 18.4, -64.6),
    'VI': ('US Virgin Islands', 'North America', 17.8, -64.8),
    'BM': ('Bermuda', 'North America', 32.3, -64.75),
    'GP': ('Guadeloupe', 'North America', 16.2, -61.5),
    'MQ': ('Martinique', 'North America', 14.6, -61.0),
    'PM': ('St Pierre & Miquelon', 'North America', 46.9, -56.3),

    # ── South America ─────────────────────────────────────────────────
    'BR': ('Brazil', 'South America', -10.0, -52.0),
    'AR': ('Argentina', 'South America', -34.0, -64.0),
    'CL': ('Chile', 'South America', -35.0, -71.0),
    'PE': ('Peru', 'South America', -9.2, -75.0),
    'CO': ('Colombia', 'South America', 4.1, -73.0),
    'EC': ('Ecuador', 'South America', -1.4, -78.2),
    'BO': ('Bolivia', 'South America', -16.3, -64.7),
    'PY': ('Paraguay', 'South America', -23.4, -58.4),
    'UY': ('Uruguay', 'South America', -32.8, -56.0),
    'VE': ('Venezuela', 'South America', 7.1, -66.0),
    'GY': ('Guyana', 'South America', 5.0, -58.9),
    'SR': ('Suriname', 'South America', 4.1, -55.9),
    'GF': ('French Guiana', 'South America', 4.0, -53.0),
    'FK': ('Falkland Islands', 'South America', -51.7, -59.2),

    # ── Africa ────────────────────────────────────────────────────────
    'MA': ('Morocco', 'Africa', 31.8, -6.5),
    'DZ': ('Algeria', 'Africa', 28.0, 2.6),
    'TN': ('Tunisia', 'Africa', 34.4, 9.5),
    'LY': ('Libya', 'Africa', 27.0, 17.5),
    'EG': ('Egypt', 'Africa', 26.8, 30.0),
    'SD': ('Sudan', 'Africa', 15.5, 30.2),
    'SS': ('South Sudan', 'Africa', 7.3, 30.3),
    'ER': ('Eritrea', 'Africa', 15.4, 38.9),
    'ET': ('Ethiopia', 'Africa', 9.1, 39.5),
    'DJ': ('Djibouti', 'Africa', 11.7, 42.6),
    'SO': ('Somalia', 'Africa', 5.2, 46.2),
    'KE': ('Kenya', 'Africa', 0.2, 37.9),
    'UG': ('Uganda', 'Africa', 1.3, 32.4),
    'RW': ('Rwanda', 'Africa', -1.9, 29.9),
    'BI': ('Burundi', 'Africa', -3.4, 29.9),
    'TZ': ('Tanzania', 'Africa', -6.4, 34.9),
    'MW': ('Malawi', 'Africa', -13.3, 34.0),
    'ZM': ('Zambia', 'Africa', -13.1, 27.9),
    'ZW': ('Zimbabwe', 'Africa', -19.0, 29.9),
    'MZ': ('Mozambique', 'Africa', -18.7, 35.5),
    'BW': ('Botswana', 'Africa', -22.3, 24.7),
    'NA': ('Namibia', 'Africa', -22.6, 17.1),
    'ZA': ('South Africa', 'Africa', -28.5, 24.7),
    'LS': ('Lesotho', 'Africa', -29.6, 28.2),
    'SZ': ('Eswatini', 'Africa', -26.5, 31.5),
    'MG': ('Madagascar', 'Africa', -19.4, 46.7),
    'MU': ('Mauritius', 'Africa', -20.3, 57.6),
    'SC': ('Seychelles', 'Africa', -4.7, 55.5),
    'KM': ('Comoros', 'Africa', -11.7, 43.4),
    'RE': ('Reunion', 'Africa', -21.1, 55.5),
    'YT': ('Mayotte', 'Africa', -12.8, 45.2),
    'CV': ('Cabo Verde', 'Africa', 15.9, -23.9),
    'AO': ('Angola', 'Africa', -12.3, 17.6),
    'CD': ('DR Congo', 'Africa', -2.9, 23.6),
    'CG': ('Republic of the Congo', 'Africa', -0.8, 15.3),
    'GA': ('Gabon', 'Africa', -0.6, 11.8),
    'GQ': ('Equatorial Guinea', 'Africa', 1.6, 10.5),
    'CM': ('Cameroon', 'Africa', 5.7, 12.7),
    'CF': ('Central African Republic', 'Africa', 6.6, 20.9),
    'TD': ('Chad', 'Africa', 15.4, 18.7),
    'NE': ('Niger', 'Africa', 17.6, 9.4),
    'NG': ('Nigeria', 'Africa', 9.1, 8.7),
    'BJ': ('Benin', 'Africa', 9.3, 2.3),
    'TG': ('Togo', 'Africa', 8.6, 1.0),
    'GH': ('Ghana', 'Africa', 7.9, -1.0),
    'CI': ('Cote d’Ivoire', 'Africa', 7.5, -5.5),
    'LR': ('Liberia', 'Africa', 6.4, -9.4),
    'SL': ('Sierra Leone', 'Africa', 8.5, -11.8),
    'GN': ('Guinea', 'Africa', 10.4, -11.3),
    'GW': ('Guinea-Bissau', 'Africa', 12.0, -14.9),
    'SN': ('Senegal', 'Africa', 14.4, -14.5),
    'GM': ('Gambia', 'Africa', 13.4, -15.4),
    'ML': ('Mali', 'Africa', 17.4, -3.5),
    'BF': ('Burkina Faso', 'Africa', 12.3, -1.6),
    'MR': ('Mauritania', 'Africa', 20.3, -10.9),
    'ST': ('Sao Tome & Principe', 'Africa', 0.2, 6.6),
}

# Countries where the advice is not "when to go" but "do not". Level is one of
# 'avoid' (reconsider or do not travel) or 'care' (parts of the country, or a
# situation that changes). The note says why, plainly, without editorialising.
#
# This is a starting point, not a substitute for government advice - which is
# exactly what the app tells the reader, with a link to check it themselves.
ADVISORIES = {
    'UA': ('avoid', 'Full-scale war. Do not travel.'),
    'RU': ('avoid', 'War, sanctions, closed airspace and a real risk of arbitrary '
                    'detention for foreign nationals. Do not travel.'),
    'BY': ('avoid', 'Detention risk for foreign nationals, and no consular help '
                    'for many. Do not travel.'),
    'SY': ('avoid', 'Armed conflict and kidnapping. Do not travel.'),
    'YE': ('avoid', 'Civil war, mines and kidnapping. Do not travel.'),
    'AF': ('avoid', 'Armed conflict, terrorism and detention risk. Do not travel.'),
    'IR': ('avoid', 'Serious risk of arbitrary arrest and detention of foreign '
                    'and dual nationals. Do not travel.'),
    'IQ': ('avoid', 'Armed conflict and kidnapping across much of the country.'),
    'LY': ('avoid', 'Armed conflict, kidnapping and no functioning consular help.'),
    'SO': ('avoid', 'Armed conflict, terrorism and kidnapping. Do not travel.'),
    'SS': ('avoid', 'Armed conflict and violent crime. Do not travel.'),
    'SD': ('avoid', 'Civil war. Do not travel.'),
    'ML': ('avoid', 'Armed conflict and kidnapping outside the capital.'),
    'BF': ('avoid', 'Armed groups and kidnapping across most of the country.'),
    'NE': ('avoid', 'Armed groups and kidnapping. Do not travel.'),
    'HT': ('avoid', 'Armed gangs control much of the capital. Do not travel.'),
    'KP': ('avoid', 'Independent travel is not possible and detention risk is real.'),
    'VE': ('avoid', 'Violent crime, and wrongful detention of foreign nationals.'),
    'MM': ('avoid', 'Civil war, conscription and arbitrary detention.'),
    'IL': ('care', 'Ongoing conflict. Areas near Gaza and the northern border '
                   'change at short notice.'),
    'PS': ('care', 'Ongoing conflict. Access is restricted and changes daily.'),
    'LB': ('care', 'Conflict on the southern border and periodic instability.'),
    'PK': ('care', 'Parts of the country, especially the border regions, are unsafe.'),
    'NG': ('care', 'Kidnapping in the north and parts of the south.'),
    'ET': ('care', 'Regional conflicts. Check which regions are open before booking.'),
    'CD': ('care', 'Armed groups in the east. The west is calmer.'),
    'CF': ('avoid', 'Armed conflict outside the capital.'),
    'EG': ('care', 'The Sinai peninsula away from the resorts is not safe.'),
    'CO': ('care', 'Some border and rural areas remain unsafe.'),
    'MX': ('care', 'Cartel violence is concentrated in specific states, not the '
                   'usual tourist routes. Check state by state.'),
    'TR': ('care', 'The Syrian border region is not safe.'),
}
